name = "tutorial_drizzle_d1"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "tutorial_drizzle_d1"
database_id = "${env.DB_REMOTE_DATABASE_ID}"
preview_database_id = "${env.DB_REMOTE_DATABASE_ID}"
