"use client"
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat as GoogleMontserrat, Outfit } from "next/font/google";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateListContext } from "./_context/UpdateListContext";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Rename to avoid conflict
const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname(); 
  const [updateList, setUpdateList] = useState(false)
  const showHeader = params === '/sign-in' || params == '/create-account' ? false : true;

  return (
    <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENTID }}>

    <html lang="en">
      <body className={outfit.className}>
        <UpdateListContext.Provider value={{updateList, setUpdateList}}>
        {showHeader && <Header/>}
        {children}
        <Toaster />
        </UpdateListContext.Provider>
      </body>
    </html>
    </PayPalScriptProvider>
  );
}